import json
from datetime import datetime, timezone
from app.database import db

class RequestLog(db.Model):
    """Stores full inspection audit logs, multi-layer risk scores, and SHAP XAI attributions."""
    __tablename__ = 'request_logs'

    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), index=True)
    ip_address = db.Column(db.String(64), nullable=False, index=True)
    method = db.Column(db.String(16), nullable=False)
    url = db.Column(db.String(2048), nullable=False)
    headers_json = db.Column(db.Text, default='{}')
    payload = db.Column(db.Text, default='')

    # Multi-Layer AMRSF Scores (0 - 100)
    final_risk_score = db.Column(db.Float, nullable=False, index=True)
    signature_score = db.Column(db.Float, default=0.0)
    encoding_suspicion = db.Column(db.Float, default=0.0)
    payload_complexity = db.Column(db.Float, default=0.0)
    ml_confidence = db.Column(db.Float, default=0.0)
    behavioral_score = db.Column(db.Float, default=0.0)
    threat_intel_score = db.Column(db.Float, default=0.0)

    # Decision & Classification
    decision = db.Column(db.String(32), nullable=False, index=True)  # Allow, Monitor, Challenge, Block
    attack_category = db.Column(db.String(64), nullable=False, index=True)
    reason = db.Column(db.Text, default='')
    shap_explanations = db.Column(db.Text, default='[]')  # JSON array of top SHAP feature impacts
    action_taken = db.Column(db.String(128), default='Allowed')

    def to_dict(self):
        try:
            shap_data = json.loads(self.shap_explanations) if self.shap_explanations else []
        except Exception:
            shap_data = []

        try:
            headers_data = json.loads(self.headers_json) if self.headers_json else {}
        except Exception:
            headers_data = {}

        return {
            'id': self.id,
            'timestamp': self.timestamp.isoformat() if self.timestamp else None,
            'ip_address': self.ip_address,
            'method': self.method,
            'url': self.url,
            'headers': headers_data,
            'payload': self.payload,
            'final_risk_score': round(self.final_risk_score, 1),
            'scores_breakdown': {
                'signature_score': round(self.signature_score, 1),
                'encoding_suspicion': round(self.encoding_suspicion, 1),
                'payload_complexity': round(self.payload_complexity, 1),
                'ml_confidence': round(self.ml_confidence, 1),
                'behavioral_score': round(self.behavioral_score, 1),
                'threat_intel_score': round(self.threat_intel_score, 1),
            },
            'decision': self.decision,
            'attack_category': self.attack_category,
            'reason': self.reason,
            'shap_explanations': shap_data,
            'action_taken': self.action_taken
        }


class AttackTimelineEvent(db.Model):
    """Reconstructs multi-stage attack campaigns for SOC dashboard timeline."""
    __tablename__ = 'attack_timeline_events'

    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), index=True)
    campaign_id = db.Column(db.String(64), index=True)
    ip_address = db.Column(db.String(64), nullable=False, index=True)
    stage = db.Column(db.String(64), nullable=False)  # Reconnaissance, Probing, Exploit Attempt, Automated Block
    attack_category = db.Column(db.String(64), nullable=False)
    description = db.Column(db.Text, nullable=False)
    risk_score = db.Column(db.Float, default=0.0)
    decision = db.Column(db.String(32), default='Monitor')

    def to_dict(self):
        return {
            'id': self.id,
            'timestamp': self.timestamp.isoformat() if self.timestamp else None,
            'campaign_id': self.campaign_id,
            'ip_address': self.ip_address,
            'stage': self.stage,
            'attack_category': self.attack_category,
            'description': self.description,
            'risk_score': round(self.risk_score, 1),
            'decision': self.decision
        }


class WAFRule(db.Model):
    """Stores custom signature rules and permanent rule suggestions generated by AMRSF."""
    __tablename__ = 'waf_rules'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), nullable=False, unique=True)
    attack_category = db.Column(db.String(64), nullable=False)
    pattern = db.Column(db.String(1024), nullable=False)  # Regex or exact pattern
    severity_score = db.Column(db.Float, default=80.0)
    is_active = db.Column(db.Boolean, default=True)
    is_auto_suggested = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    def to_dict(self):
        return {
            'id': self.id,
            'name': self.name,
            'attack_category': self.attack_category,
            'pattern': self.pattern,
            'severity_score': self.severity_score,
            'is_active': self.is_active,
            'is_auto_suggested': self.is_auto_suggested,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }


class ThreatIP(db.Model):
    """Cached Threat Intelligence IP reputation records."""
    __tablename__ = 'threat_ips'

    id = db.Column(db.Integer, primary_key=True)
    ip_address = db.Column(db.String(64), unique=True, nullable=False, index=True)
    reputation_score = db.Column(db.Float, default=0.0)  # 0 to 100
    threat_category = db.Column(db.String(64), default='Clean')
    source = db.Column(db.String(64), default='AbuseIPDB')
    last_checked = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    def to_dict(self):
        return {
            'id': self.id,
            'ip_address': self.ip_address,
            'reputation_score': self.reputation_score,
            'threat_category': self.threat_category,
            'source': self.source,
            'last_checked': self.last_checked.isoformat() if self.last_checked else None
        }
